import './globals.css'
import type { Metadata } from 'next'
import React from "react";
import Layout from "@/components/layout";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className={"bg-gray-200 dark:bg-gray-800 max-h-screen"}>
        <Layout>
          {children}
        </Layout>
    </body>
    </html>
  )
}
